Library_maneger/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('api/', include('library.api_urls')),
]

library/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from library.views import BookListView
from library.views import BookDetailView
from library.views import search_results

urlpatterns = [
    path('', BookListView.as_view(), name='home'),
    path('book/<int:pk>/', BookDetailView.as_view(), name='book_detail'),
    path('search/', search_results, name='search_results'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users import views
from users.views import RegisterView
from users.views import taken_books_view
from users.views import take_book

from users.views import wishlist_book, remove_from_wishlist, wishlist_view
from users.views import mark_notifications_as_read

app_name = 'users'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('taken_books/', taken_books_view, name='taken_books'),
    path('take_book/<int:book_id>/', take_book, name='take_book'),
    path('wishlist_book/<int:book_id>/', wishlist_book, name='wishlist_book'),
    path('remove_from_woshlist/<int:book_id>', remove_from_wishlist, name='remove_from_wishlist'),
    path('wishlist_books', wishlist_view, name='wishlist_books'),
    path('mark_notifications_as_read/', mark_notifications_as_read, name='mark_notifications_as_read'),
]

library/models.py
from django.db import models


class Author(models.Model):
    name = models.CharField('Name', max_length=63)

    class Meta:
        verbose_name = 'Author'
        verbose_name_plural = 'Authors'

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField('Name', max_length=63)

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField('Title', max_length=63)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, null=True)
    category = models.ManyToManyField(Category, blank=False)
    cover = models.ImageField(upload_to='media/', blank=True)
    stock = models.IntegerField(default=0)
    times_taken = models.IntegerField(default=0)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Book'
        verbose_name_plural = 'Books'

library/views.py
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView, DetailView
from django.utils import timezone
from django.db.models import Count
from datetime import timedelta

from rest_framework.permissions import IsAuthenticated
from rest_framework.views import APIView

from library.models import Book
from library.models import Category
from users.models import TakenBook
from users.models import WishlistBook
from users.models import ReturnedBook
from users.models import Notification

from rest_framework import viewsets, generics
from rest_framework.response import Response
from rest_framework.decorators import action

from library.serializers import BookSerializer
from library.serializers import TakenBookSerializer
from library.serializers import WishlistBookSerializer


class BookListView(ListView):
    model = Book
    template_name = 'library/home.html'
    context_object_name = 'books'
    paginate_by = 44

    def get_queryset(self):
        queryset = Book.objects.all()
        category_id = self.request.GET.get('category')
        if category_id:
            queryset = queryset.filter(category__id=category_id)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.annotate(book_count=Count('book'))
        context['all_book_count'] = Book.objects.count()
        context['selected_category'] = self.request.GET.get('category')

        if self.request.user.is_authenticated:
            context['wishlist_books'] = WishlistBook.objects.filter(user=self.request.user).values_list('book_id', flat=True)
            notifications = Notification.objects.filter(user=self.request.user).order_by('-created_at')
            context['notifications'] = notifications
            context['unread_notifications'] = notifications.filter(read=False)

        return context


class BookDetailView(DetailView):
    model = Book
    template_name = 'library/book_detail.html'
    context_object_name = 'book'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        if self.request.user.is_authenticated:
            context['wishlist_books'] = WishlistBook.objects.filter(user=self.request.user).values_list('book_id', flat=True)

        return context


class BookViewSet(viewsets.ModelViewSet):
    queryset = Book.objects.all()
    serializer_class = BookSerializer

    @action(detail=False, methods=['get'])
    def top_books(self, request):
        top_books = Book.objects.annotate(times_taken_count=Count('times_taken')).order_by('-times_taken_count')[:10]
        serializer = self.get_serializer(top_books, many=True)
        return Response(serializer.data)

    @action(detail=False, methods=['get'])
    def sorted_books(self, request):
        sort_by = request.query_params.get('sort_by', 'title')
        books = Book.objects.all().order_by(sort_by)
        serializer = self.get_serializer(books, many=True)
        return Response(serializer.data)


class TakenBookViewSet(viewsets.ModelViewSet):
    queryset = TakenBook.objects.all()
    serializer_class = TakenBookSerializer

    @action(detail=False, methods=['get'])
    def statistics(self, request):
        stats = {
            'total_books_returned': ReturnedBook.objects.count(),
            'books_awaiting': TakenBook.objects.filter(status='Awaiting').count(),
            'books_taken': TakenBook.objects.filter(status='Taken').count(),
        }
        return Response(stats)

    @action(detail=False, methods=['get'])
    def top_popular_books(self, request):
        popular_books = Book.objects.annotate(taken_count=Count('takenbook')).order_by('-taken_count')[:10]
        serializer = BookSerializer(popular_books, many=True)
        return Response(serializer.data)

    @action(detail=False, methods=['get'])
    def top_overdue_books(self, request):
        overdue_books = TakenBook.objects.filter(status='Taken', date_taken__lte=timezone.now() - timedelta(weeks=1)).order_by('-date_taken')[:100]
        serializer = self.get_serializer(overdue_books, many=True)
        return Response(serializer.data)

    @action(detail=False, methods=['get'])
    def top_users_with_overdue_books(self, request):
        top_users = TakenBook.objects.filter(status='Taken', date_taken__lte=timezone.now() - timedelta(weeks=1)).values('user').annotate(overdue_count=Count('id')).order_by('-overdue_count')[:100]
        return Response(top_users)


class WishlistBookViewSet(viewsets.ModelViewSet):
    queryset = WishlistBook.objects.all()
    serializer_class = WishlistBookSerializer


def search_results(request):
    query = request.GET.get('q')
    category_id = request.GET.get('category')

    if query:
        results = Book.objects.filter(title__icontains=query)
    else:
        results = Book.objects.none()

    if category_id:
        results = results.filter(category__id=category_id)

    paginator = Paginator(results, 40)
    page_number = request.GET.get('page')

    try:
        results = paginator.page(page_number)
    except PageNotAnInteger:
        results = paginator.page(1)
    except EmptyPage:
        results = paginator.page(paginator.num_pages)

    context = {
        'paginator': paginator,
        'results': results,
        'query': query,
        'category_id': category_id,
    }

    return render(request, 'library/search_results.html', context)

library/templates/library/book_detail.html
{% extends 'library/home.html' %}
{% load static %}

{%  block title %}
    {{ book.title }}
{%  endblock %}


{% block content %}
    <div class="book_detail_cover">
        {% if book.cover %}
            <img src="{{ book.cover.url }}" alt="{{ book.title }}" class="book_cover_icon" draggable="false">
        {% else %}
            <img src="{% static 'library/images/no-image.png' %}" alt="{{ book.title }}" class="no_book_cover_icon" draggable="false">
        {% endif %}
    </div>
    <div class="book_detail_description">
        <div class="book_detail_title">
            {{ book.title }}
        </div>
        <div class="book_detail_divide_line"></div>
        <div class="book_detail_author">
            Author: {{ book.author }}
        </div>
    <div class="times_taken">
        Times taken: {{ book.times_taken }}
    </div>
    {% if book.stock > 0 %}
        {% if user.is_authenticated and book in user.taken_books.all %}
            <button disabled class="already_taken_button" id="book_detail_take_book">Already Taken</button>
        {% else %}
            <form method="POST" action="{% url 'users:take_book' book.id %}">
                {% csrf_token %}
                <button type="submit" class="take_button" id="book_detail_take_book">Take Book</button>
            </form>
        {% endif %}
    {% else %}
        {% if user.is_authenticated and book in user.taken_books.all %}
            <button disabled class="already_taken_button" id="book_detail_take_book">Already Taken</button>
        {% elif book.id in wishlist_books %}
            <form method="POST" action="{% url 'users:remove_from_wishlist' book.id %}">
                {% csrf_token %}
                <button type="submit" class="remove_from_wishlist" id="book_detail_take_book">Remove</button>
            </form>
        {% else %}
            <form method="POST" action="{% url 'users:wishlist_book' book.id %}">
                {% csrf_token %}
                <button type="submit" class="wishlist_button" id="book_detail_take_book">Wishlist</button>
            </form>
        {% endif %}
    {% endif %}
    </div>
{% endblock %}

library/templates/library/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Library
        {% endblock %}
    </title>
    <link rel="stylesheet" type="text/css" href="{% static 'library/css/main.css' %}">
</head>
<body>
    <div class="header">
        <a href="{% url 'home' %}">
            <div class="logo">
                <img rel="stylesheet" class="georgia_logo" src="{% static 'library/images/georgia.png' %}" alt="Home page" draggable="false">
                <img src="{% static 'library/images/logo_text.png' %}" alt="Home page" class="logo_text" draggable="false">
            </div>
        </a>

        <a href="{% url 'home' %}">
            <button class="home_button">
                Home
            </button>
        </a>
        {% csrf_token %}
        {% if not user.is_authenticated %}
            <a href="{% url 'users:login' %}">
                <button class="login_button">
                    Login
                </button>
            </a>
            <a href="{% url 'users:register' %}">
                <button class="register_button">
                    Register
                </button>
            </a>
        {% else %}
            <div class="user_panel">

                <button class="notifications_button" id="notification-button">
                    <img class="notifications_icon" src="{% static 'library/images/notifications.png' %}" alt="">
                    <span class="unread_count" id="unread-count">{% if unread_notifications %}{{ unread_notifications|length }}{% endif %}</span>
                </button>
                <div class="notifications_panel hidden" id="notification-panel">
                {% if not notifications %}
                    <div class="notification">
                                <p>No notifications yet</p>
                            </div>
                {% else %}
                    {% for notification in notifications %}
                        {% if notification.link %}
                            <a href="{{ notification.link }}">
                            <div class="notification">
                                <p>{{ notification.message }}</p>
                            </div>
                            </a>
                        {% endif %}
                    {% endfor %}
                {% endif %}
                </div>
                <a href="{% url 'users:taken_books' %}">
                    <button class="my_books_button">
                        <img rel="stylesheet" class="book_icon" src="{% static 'library/images/books.png' %}" alt="" draggable="false">
                        My books
                    </button>
                </a>
            </div>

            <a href="{% url 'users:logout' %}">
                <button class="login_button">
                    Logout
                </button>
            </a>
        {% endif %}
    </div>

    <div class="content">

        <form action="{% url 'search_results' %}" method="GET" class="search_bar">
            <input type="text" class="search_field" name="q" placeholder="Browse books...">
            <button type="submit" class="search_button">
                <img src="{% static 'library/images/search.png' %}" alt="" class="search_icon" draggable="false">
            </button>
        </form>

        <div class="categories">
            Categories: <br/>
            <a href="{% url 'home' %}" style="font-weight: normal">
                - All categories ({{ all_book_count }})
            </a><br/>
            {% for category in categories %}
                <a href="{% url 'home' %}?category={{ category.id }}" style="font-weight: normal">
                    - {{ category.name }} ({{ category.book_count }})
                </a><br/>
            {% endfor %}
        </div>

        <div class="books">
            {% block content %}
                {% for book in books %}
                    <a href="{% url 'book_detail' book.id%}">
                    <div class="book">

                    <div class="book_cover">
                        {% if book.cover %}
                            <img src="{{ book.cover.url }}" alt="{{ book.title }}" class="book_cover_icon" draggable="false">
                        {% else %}
                            <img src="{% static 'library/images/no-image.png' %}" alt="{{ book.title }}" class="no_book_cover_icon" draggable="false">
                        {% endif %}

                        {% if book.stock > 0 %}
                            <div class="in_stock">
                            <img class="in_stock_icon" src="{% static 'library/images/in_stock.png' %}" alt="">
                                In stock
                            </div>
                        {% else %}
                            <div class="out_of_stock">
                            <img class="out_of_stock_icon" src="{% static 'library/images/out_of_stock.png' %}" alt="">
                                Out of stock
                            </div>
                        {% endif %}
                        <br/>
                        <div class="author">
                            Author: {{ book.author }}
                        </div>
                    </div>

                    <div class="book_title">
                        {{ book.title }}
                    </div>

                    {% if book.stock > 0 %}
                        {% if user.is_authenticated and book in user.taken_books.all %}
                            <button disabled class="already_taken_button" id="take_book">Already Taken</button>
                        {% else %}
                            <form method="POST" action="{% url 'users:take_book' book.id %}">
                                {% csrf_token %}
                                <button type="submit" class="take_button" id="take_book">Take Book</button>
                            </form>
                        {% endif %}
                    {% else %}
                        {% if user.is_authenticated and book in user.taken_books.all %}
                            <button disabled class="already_taken_button" id="take_book">Already Taken</button>
                        {% elif book.id in wishlist_books %}
                            <form method="POST" action="{% url 'users:remove_from_wishlist' book.id %}">
                                {% csrf_token %}
                                <button type="submit" class="remove_from_wishlist" id="take_book">Remove</button>
                            </form>
                        {% else %}
                            <form method="POST" action="{% url 'users:wishlist_book' book.id %}">
                                {% csrf_token %}
                                <button type="submit" class="wishlist_button" id="take_book">Wishlist</button>
                            </form>
                        {% endif %}
                    {% endif %}
                    </div>
                    </a>
                {% endfor %}
                <div class="num_of_pages">
                {% for p in paginator.page_range %}
                    {% if page_obj.has_other_pages %}
                        <a class="page_number" href="?page={{p}}">
                        {% if p == page_obj.number %}
                            <div class="current_page_button">
                                {{p}}
                            </div>
                        {% else %}
                            <div class="page_number_button">
                                {{p}}
                            </div>
                        {% endif %}
                        </a>
                    {% endif %}
                {% endfor %}
                </div>
            {% endblock %}
        </div>
    </div>
    <div class="footer">
    </div>

<script src="{% static 'library/js/notifications.js' %}"></script>

</body>
</html>

library/templates/library/search_results.html
{% extends 'library/home.html' %}
{% load static %}


{% block content %}
    <div class="search_results_text">
        Search Results for "{{ query }}":
    </div>
        {% for book in results %}
            <a href="{% url 'book_detail' book.id%}">
            <div class="book">
                <div class="book_cover">
                    {% if book.cover %}
                        <img src="{{ book.cover.url }}" alt="{{ book.title }}" class="book_cover_icon" draggable="false">
                    {% else %}
                        <img src="{% static 'library/images/no-image.png' %}" alt="{{ book.title }}" class="no_book_cover_icon" draggable="false">
                    {% endif %}

                    {% if book.stock > 0 %}
                        <div class="in_stock">
                        <img class="in_stock_icon" src="{% static 'library/images/in_stock.png' %}" alt="">
                            In stock
                        </div>
                    {% else %}
                        <div class="out_of_stock">
                        <img class="out_of_stock_icon" src="{% static 'library/images/out_of_stock.png' %}" alt="">
                            Out of stock
                        </div>
                    {% endif %}
                    <br/>
                    <div class="author">
                        Author: {{ book.author }}
                    </div>
                </div>

                <div class="book_title">
                    {{ book.title }}
                </div>
                    {% if book.stock > 0 %}
                        {% if user.is_authenticated and book in user.taken_books.all %}
                            <button disabled class="already_taken_button" id="take_book">Already Taken</button>
                        {% else %}
                            <form method="POST" action="{% url 'users:take_book' book.id %}">
                                {% csrf_token %}
                                <button type="submit" class="take_button" id="take_book">Take Book</button>
                            </form>
                        {% endif %}
                    {% else %}
                        {% if user.is_authenticated and book in user.taken_books.all %}
                            <button disabled class="already_taken_button" id="take_book">Already Taken</button>
                        {% elif book.id in wishlist_books %}
                            <form method="POST" action="{% url 'users:remove_from_wishlist' book.id %}">
                                {% csrf_token %}
                                <button type="submit" class="remove_from_wishlist" id="take_book">Remove</button>
                            </form>
                        {% else %}
                            <form method="POST" action="{% url 'users:wishlist_book' book.id %}">
                                {% csrf_token %}
                                <button type="submit" class="wishlist_button" id="take_book">Wishlist</button>
                            </form>
                        {% endif %}
                    {% endif %}
                </div>
            </a>

        {% empty %}
            No results found.
        {% endfor %}
            <div class="num_of_pages" style="display: table">
                {% for p in paginator.page_range %}
                    {% if results.has_other_pages %}
                        <a class="page_number" href="?q={{ query }}&page={{ p }}">
                            {% if p == results.number %}
                                <div class="current_page_button">
                                    {{ p }}
                                </div>
                            {% else %}
                                <div class="page_number_button">
                                    {{ p }}
                                </div>
                            {% endif %}
                        </a>
                    {% endif %}
                {% endfor %}
            </div>
{% endblock %}