Library_maneger/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('api/', include('library.api_urls')),
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users import views
from users.views import RegisterView
from users.views import taken_books_view
from users.views import take_book

from users.views import wishlist_book, remove_from_wishlist, wishlist_view
from users.views import mark_notifications_as_read

app_name = 'users'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('taken_books/', taken_books_view, name='taken_books'),
    path('take_book/<int:book_id>/', take_book, name='take_book'),
    path('wishlist_book/<int:book_id>/', wishlist_book, name='wishlist_book'),
    path('remove_from_woshlist/<int:book_id>', remove_from_wishlist, name='remove_from_wishlist'),
    path('wishlist_books', wishlist_view, name='wishlist_books'),
    path('mark_notifications_as_read/', mark_notifications_as_read, name='mark_notifications_as_read'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save, post_delete, pre_save
from django.dispatch import receiver
from django.db import models, transaction
from django.urls import reverse

from library.models import Book


class User(AbstractUser):
    taken_books = models.ManyToManyField(Book, through='TakenBook', related_name='users')


class TakenBook(models.Model):
    STATUS_CHOICES = [
        ('Awaiting', 'Awaiting'),
        ('Taken', 'Taken'),
        ('Returned', 'Returned')
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    date_taken = models.DateTimeField(auto_now_add=True)
    status = models.CharField('Status', max_length=10, choices=STATUS_CHOICES, default='Awaiting')

    def __str__(self):
        return f"{self.user.username} booked {self.book.title} on {self.date_taken}"

    class Meta:
        verbose_name = 'Taken Book'
        verbose_name_plural = 'Taken Books'


class ReturnedBook(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    date_taken = models.DateTimeField()
    date_returned = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} returned {self.book.title} on {self.date_returned}"

    class Meta:
        verbose_name = 'Returned Book'
        verbose_name_plural = 'Returned Books'


class WishlistBook(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} wishlisted {self.book.title}"


class Notification(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.CharField(max_length=127)
    link = models.URLField(null=True, blank=True)
    read = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Notification for {self.user.username}"


@receiver(post_save, sender=TakenBook)
def decrease_book_stock(sender, instance, created, **kwargs):
    if created:
        instance.book.stock -= 1
        instance.book.save()


@receiver(pre_save, sender=TakenBook)
def create_returned_book(sender, instance, **kwargs):
    if instance.pk:
        previous_instance = TakenBook.objects.get(pk=instance.pk)
        if previous_instance.status != 'Returned' and instance.status == 'Returned':

            def delete_and_create_returned_book():
                ReturnedBook.objects.create(
                    user=instance.user,
                    book=instance.book,
                    date_taken=instance.date_taken
                )
                instance.delete()

            transaction.on_commit(delete_and_create_returned_book)


@receiver(post_delete, sender=TakenBook)
def increase_book_stock_on_book_return(sender, instance, **kwargs):
    instance.book.stock += 1
    instance.book.save()
    notify_wishlist_users(instance.book)


def notify_wishlist_users(book):
    wishlist_books = WishlistBook.objects.filter(book=book)
    for wishlist_book in wishlist_books:
        user = wishlist_book.user
        message = f'The book "{book.title}" is in stock!'
        link = reverse('book_detail', args=[book.id])
        Notification.objects.create(user=user, message=message, link=link)


@receiver(pre_save, sender=Book)
def notify_wishlist_users_on_book_stock_increase(sender, instance, **kwargs):
    if instance.pk:
        previous_instance = Book.objects.get(pk=instance.pk)
        if instance.stock > previous_instance.stock:
            notify_wishlist_users(instance)


@receiver(post_save, sender=TakenBook)
def delete_wishlisted_book(sender, instance, created, **kwargs):
    if created:
        wishlisted_book = WishlistBook.objects.filter(user=instance.user, book=instance.book).first()
        if wishlisted_book:
            wishlisted_book.delete()

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Email',
                               widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Password',
                               widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()


class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'password1', 'password2']

users/views.py
from django.contrib.auth import logout, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse, reverse_lazy
from django.views.decorators.http import require_POST
from django.views.generic import FormView

from library.models import Book
from users.forms import LoginUserForm, RegisterForm
from users.models import TakenBook
from users.models import WishlistBook
from users.models import Notification


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'users/login.html'
    extra_context = {'title': 'Login'}

    def form_valid(self, form):
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('home')


class RegisterView(FormView):
    template_name = 'users/register.html'
    form_class = RegisterForm
    success_url = reverse_lazy('home')
    extra_context = {'title': 'Register'}

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return super().form_valid(form)


def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('home'))


@login_required
def taken_books_view(request):
    user = request.user
    taken_books = user.takenbook_set.all()
    has_taken_books = taken_books.exists()
    return render(request, 'users/taken_books.html', {'taken_books': taken_books,
                                                      'title': 'Taken books',
                                                      'has_taken_books': has_taken_books})


@login_required
def take_book(request, book_id):
    if not request.user.is_authenticated:
        return redirect('users/login')

    book = get_object_or_404(Book, id=book_id)

    if TakenBook.objects.filter(user=request.user, book=book).exists():
        return redirect('home')

    if book.stock > 0:
        TakenBook.objects.create(user=request.user, book=book, status='Awaiting')
        book.times_taken += 1
        book.save()

    return redirect('home')


@login_required
def wishlist_book(request, book_id):
    book = get_object_or_404(Book, id=book_id)
    WishlistBook.objects.create(user=request.user, book=book)
    return redirect('home')


@login_required
def remove_from_wishlist(request, book_id):
    book = get_object_or_404(Book, id=book_id)
    WishlistBook.objects.filter(user=request.user, book=book).delete()
    return redirect('home')


@login_required
def wishlist_view(request):
    user = request.user
    wishlist_books = WishlistBook.objects.filter(user=request.user)
    return render(request, 'users/wishlist.html', context={'wishlist_books': wishlist_books, 'title': 'Wishlist'})


@require_POST
def mark_notifications_as_read(request):
    if request.user.is_authenticated:
        Notification.objects.filter(user=request.user, read=False).update(read=True)
        return JsonResponse({'status': 'success'})
    return JsonResponse({'status': 'error'}, status=400)

users/templates/users/login.html
{% extends 'library/home.html' %}


{%  block title %}
    {{ title }}
{%  endblock %}


{% block content %}
<form method="post" class="login_form">
    {% csrf_token %}

    <div class="form-group">
        <label for="username">Username:</label>
        <input id="username" type="text" name="username" class="form-control" placeholder="Enter username" required autofocus>
    </div>

    <div class="form-group">
        <label for="password">Password:</label>
        <input id="password" type="password" name="password" class="form-control" placeholder="Enter password" required>
    </div>

    <button type="submit" class="btn">Log in</button>
    </form>
{% endblock %}

users/templates/users/register.html
{% extends 'library/home.html' %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
<form method="POST" class="register_form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Register</button>
</form>
{% endblock %}

users/templates/users/taken_books.html
{% extends 'library/home.html' %}
{% load static %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
    <div class="my_books_buttons">
    <a href="{% url 'users:taken_books' %}">
    <button class="taken_books_button">
        Taken books
    </button>
    </a>
    <a href="{% url 'users:wishlist_books' %}">
    <button class="wishlist_books_button">
        Wishlist books
    </button>
    </a>
    </div>
    {% if has_taken_books %}
        <div class="books">
        {% for taken_book in taken_books %}
            <a href="{% url 'book_detail' taken_book.book.id %}">
            <div class="book">
                <div class="book_cover">
                    {% if taken_book.book.cover %}
                        <img src="{{ taken_book.book.cover.url }}" alt="{{ taken_book.book.title }}" class="book_cover_icon" draggable="false">
                    {% else %}
                        <img src="{% static 'library/images/no-image.png' %}" alt="{{ taken_book.book.title }}" class="no_book_cover_icon" draggable="false">
                    {% endif %}
                    <div class="date_taken">
                        Taken on: <br/>{{ taken_book.date_taken }}
                    </div>
                </div>
                <div class="book_title">
                    {{ taken_book.book.title }}<br/>
                </div>

                <div class="book_status">
                    <a style="font-weight: bold">Status:</a>
                    {% if taken_book.status == 'Taken' %}
                        <a style="background-color: green; color: white;font-family: Calibri; padding: 1px 8px; font-style: italic">{{ taken_book.status }}</a>
                    {% else %}
                        <a style="background-color: gold; color: black;font-family: Calibri; padding: 1px 8px; font-style: italic">{{ taken_book.status }}</a>
                    {% endif %}
                </div>
            </div>
            </a>
        {% endfor %}
        </div>
    {% else %}
        <div style="margin-top: 100px; font-size: 20px">
            No books taken
        </div>
    {% endif %}
{% endblock %}

users/templates/users/wishlist.html
{% extends 'library/home.html' %}
{% load static %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
    <div class="my_books_buttons">
        <a href="{% url 'users:taken_books' %}">
        <button class="taken_books_button">
            Taken books
        </button>
        </a>
        <a href="{% url 'users:wishlist_books' %}">
        <button class="wishlist_books_button">
            Wishlist books
        </button>
        </a>
    </div>
    {% if wishlist_books %}
        {% for wishlisted_book in wishlist_books %}
            <a href="{% url 'book_detail' wishlisted_book.book.id%}">
            <div class="book">

            <div class="book_cover">
                {% if wishlisted_book.book.cover %}
                    <img src="{{ wishlisted_book.book.cover.url }}" alt="{{ wishlisted_book.book.title }}" class="book_cover_icon" draggable="false">
                {% else %}
                    <img src="{% static 'library/images/no-image.png' %}" alt="{{ wishlisted_book.book.title }}" class="no_book_cover_icon" draggable="false">
                {% endif %}

                {% if wishlisted_book.book.stock > 0 %}
                    <div class="in_stock">
                    <img class="in_stock_icon" src="{% static 'library/images/in_stock.png' %}" alt="">
                        In stock
                    </div>
                {% else %}
                    <div class="out_of_stock">
                    <img class="out_of_stock_icon" src="{% static 'library/images/out_of_stock.png' %}" alt="">
                        Out of stock
                    </div>
                {% endif %}
                <br/>
                <div class="author">
                    Author: {{ wishlisted_book.book.author }}
                </div>
            </div>

            <div class="book_title">
                {{ wishlisted_book.book.title }}
            </div>
                    <form method="POST" action="{% url 'users:remove_from_wishlist' wishlisted_book.book.id %}">
                        {% csrf_token %}
                        <button type="submit" class="remove_from_wishlist" id="take_book">Remove</button>
                    </form>
            </div>
            </a>
        {% endfor %}
    {% else %}
        <div style="margin-top: 100px; font-size: 20px">
            No books wishlisted
        </div>
    {% endif %}
{% endblock %}